#!/usr/bin/env bash
# Populate /opt/openclaw/.env with secrets and (re)start the bot.
# Safe to re-run. Run with sudo on the VM.
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/openclaw}"
ENV_FILE="${INSTALL_DIR}/.env"
COMPOSE_FILE="${INSTALL_DIR}/bot/docker-compose.yml"

if [[ $EUID -ne 0 ]]; then
    echo "Please run as root (sudo $0)" >&2
    exit 1
fi

umask 077
mkdir -p "${INSTALL_DIR}"

prompt() {
    local name="$1" current="$2" default="${3:-}" value=""
    if [[ -n "${current}" ]]; then
        read -r -p "${name} [keep existing] " value
        if [[ -z "${value}" ]]; then
            echo "${current}"
            return
        fi
    else
        read -r -p "${name}${default:+ [${default}]} " value
        if [[ -z "${value}" && -n "${default}" ]]; then
            echo "${default}"
            return
        fi
    fi
    echo "${value}"
}

# Load existing values if present
declare -A existing=()
if [[ -f "${ENV_FILE}" ]]; then
    while IFS='=' read -r k v; do
        [[ "${k}" =~ ^[A-Z_]+$ ]] || continue
        existing["${k}"]="${v}"
    done <"${ENV_FILE}"
fi

echo "== openclaw finish-setup =="
echo "Writing to ${ENV_FILE} (mode 600, root:root)."
echo

TELEGRAM_BOT_TOKEN=$(prompt "TELEGRAM_BOT_TOKEN:" "${existing[TELEGRAM_BOT_TOKEN]:-}")
TELEGRAM_ALLOWED_USER_IDS=$(prompt "TELEGRAM_ALLOWED_USER_IDS (comma-separated):" "${existing[TELEGRAM_ALLOWED_USER_IDS]:-}")
ANTHROPIC_API_KEY=$(prompt "ANTHROPIC_API_KEY:" "${existing[ANTHROPIC_API_KEY]:-}")
CLAUDE_MODEL=$(prompt "CLAUDE_MODEL:" "${existing[CLAUDE_MODEL]:-}" "claude-sonnet-4-5")
GH_TOKEN=$(prompt "GH_TOKEN (GitHub PAT for /pr command, optional):" "${existing[GH_TOKEN]:-}")

cat >"${ENV_FILE}" <<EOF
# openclaw runtime config
# Generated by finish-setup.sh — do not commit.
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_ALLOWED_USER_IDS=${TELEGRAM_ALLOWED_USER_IDS}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
CLAUDE_MODEL=${CLAUDE_MODEL}
GH_TOKEN=${GH_TOKEN}
EOF

# Preserve any extra keys not managed by this script (e.g. OPENCLAW_GATEWAY_TOKEN)
for key in "${!existing[@]}"; do
    case "${key}" in
        TELEGRAM_BOT_TOKEN|TELEGRAM_ALLOWED_USER_IDS|ANTHROPIC_API_KEY|CLAUDE_MODEL|GH_TOKEN) ;;
        *) echo "${key}=${existing[${key}]}" >> "${ENV_FILE}" ;;
    esac
done

chmod 600 "${ENV_FILE}"
chown root:root "${ENV_FILE}"

echo
echo "Restarting bot…"
docker compose -f "${COMPOSE_FILE}" pull 2>/dev/null || true
docker compose -f "${COMPOSE_FILE}" up -d --build

echo
echo "Done. Tail logs with:"
echo "  docker logs -f openclaw-bot"
